#!/usr/bin/env bash
# Configure HAproxy

apt-get -y update
apt-get -y install haproxy
sudo echo "$CONF" >> /etc/haproxy/haproxy.cfg
echo frontend front
	 bind *:80
	 mode http
	 default_backend back

backend back
    balance roundrobin
    server 965-web-01 35.243.184.34:80 check
    server 965-web-02 107.21.164.251:80 check

sudo service haproxy restart
