#!/bin/bash
man(2) holberton man page

NAME
 holberton - become a full-stack software engineer.

SYNOPSIS
 holberton [STUDENTNAME]

DESCRIPTION
 Holberton School is a project-based alternative to college for the next generation of software engineers.

OPTIONS
 holberton does not take any option. However, you can supply studentname.

SEE ALSO
 peerlearning(2), projectbased(2), fullstack(2), Betty(1)

BUGS
 No known bugs.

AUTHOR
 Julien Barbier, Silvain Kalache, Sophie Barbier, Guillaume Salva, Kris Gautier and all the Holberton mentors

0.32  04 May 2015 man(2)
